version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    restart: always
  app:
    image: mytsyaispat/startup_pet_project:v1
    container_name: application
    environment:
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_DATABASE: db
      DB_PORT: 5432
    ports:
      - "8090:8080"
    depends_on:
      - db